In [6]:
path1_RO = "data/Fixations/Rectangle-OK-1920-1080/"
path2list_RO = [str(i) for i in list(range(1,56))]
path3_RO ="_RO.tsv"

ALLPathsRO = []
for num in path2list_RO:
    path = path1_RO + num + path3_RO
    ALLPathsRO.append(path)

path1_RS = "data/Fixations/Rectangle-Smell-1920-1080/"
path2list_RS = [str(i) for i in list(range(1,56))]
path3_RS = "_RS.tsv"

ALLPathsRS = []
for num in path2list_RS:
    path = path1_RS + num + path3_RS
    ALLPathsRS.append(path)


path1_VO = "data/Fixations/Vehicle-OK-1920-1080/"
path2list_VO = [str(i) for i in list(range(1,56))]
path3_VO = "_VO.tsv"

ALLPathsVO = []
for num in path2list_VO:
    path = path1_VO + num + path3_VO
    ALLPathsVO.append(path)


path1_VS = "data/Fixations/Vehicle-Smell-1920-1080/"
path2list_VS = [str(i) for i in list(range(1,56))]
path3_VS = "_VS.tsv"

ALLPathsVS = []
for num in path2list_VS:
    path = path1_VS + num + path3_VS
    ALLPathsVS.append(path)
    
ALLPaths = []

for path in ALLPathsRO:
    try:
        dfTest = pd.read_csv(path,delimiter = '\t',header=0)
        ALLPaths.append(path)
        dfTest = []
    except:
        pass
    
for path in ALLPathsRS:
    try:
        dfTest = pd.read_csv(path,delimiter = '\t',header=0)
        ALLPaths.append(path)
        dfTest = []
    except:
        pass
    
for path in ALLPathsVO:
    try:
        dfTest = pd.read_csv(path,delimiter = '\t',header=0)
        ALLPaths.append(path)
        dfTest = []
    except:
        pass

for path in ALLPathsVS:
    try:
        dfTest = pd.read_csv(path,delimiter = '\t',header=0)
        ALLPaths.append(path)
        dfTest = []
    except:
        pass

In [7]:
import pandas as pd

NEWDATA = []

for path in ALLPaths:
    newDF = pd.read_csv(path,delimiter = '\t',header = 0)
    NEWDATA.append(newDF)

In [9]:
NEWDATA[0]

,Unnamed: 0,ExportDate,StudioVersionRec,StudioProjectName,StudioTestName,ParticipantName,RecordingName,RecordingDate,RecordingDuration,RecordingResolution,...,DistanceLeft,DistanceRight,PupilLeft,PupilRight,ValidityLeft,ValidityRight,IRMarkerCount,IRMarkerID,PupilGlassesRight,Unnamed: 85
0,0,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,NaN,NaN,NaN,NaN,4,4,NaN,NaN,NaN,NaN
1,1,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,"641,80","641,80","3,55","3,47",0,0,NaN,NaN,NaN,NaN
2,2,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,"641,97","641,97","3,39","3,33",0,0,NaN,NaN,NaN,NaN
3,3,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,"641,85","641,85","3,04","2,96",0,0,NaN,NaN,NaN,NaN
4,4,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,"641,78","641,78","3,01","2,97",0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,116,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,"639,89","639,89","3,23","3,20",0,0,NaN,NaN,NaN,NaN
117,117,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,NaN,NaN,NaN,NaN,4,4,NaN,NaN,NaN,NaN
118,118,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,"639,80","639,80","3,26","3,20",0,0,NaN,NaN,NaN,NaN
119,119,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,NaN,NaN,NaN,NaN,4,4,NaN,NaN,NaN,NaN
120,120,05.02.2019,3.3.2,MT_Fabian,Code-Test,n.a.,n.a.,16.10.2018,309038,1920 x 1080,...,NaN,NaN,NaN,NaN,4,4,NaN,NaN,NaN,NaN

In [17]:
columns = len(NEWDATA[0].columns)
newColumns=[]
for i in list(range(0,columns)):
    newColumns.append(str(i))

In [18]:
for dfNum in list(range(len(NEWDATA))):
    NEWDATA[dfNum].ParticipantName = "n.a."
    NEWDATA[dfNum].RecordingName = "n.a."
    NEWDATA[dfNum].ExportDate = "n.a."
    NEWDATA[dfNum].StudioVersionRec = "n.a."
    NEWDATA[dfNum].StudioProjectName = "n.a"
    NEWDATA[dfNum].StudioTestName = "n.a."
    NEWDATA[dfNum].RecordingDate = "n.a."
    NEWDATA[dfNum].columns = newColumns

In [19]:
for df,pathname in zip(NEWDATA,ALLPaths):
    df.to_csv(pathname, sep = "\t")

In [20]:
for path in ALLPaths:
    try:
        with open(path,'r') as file:
            a = pd.read_csv(file)
            print(a)
    except:
        pass

In [21]:
path = "data/Fixations/Fixations.tsv"
dfNorm = pd.read_csv(path,delimiter='\t',header = 0)
dfNorm.ParticipantName = "n.a."
dfNorm.RecordingName = "n.a."

dfNorm.ExportDate = "n.a."
dfNorm.StudioVersionRec = "n.a."
dfNorm.StudioProjectName = "n.a"
dfNorm.StudioTestName = "n.a."
dfNorm.RecordingDate = "n.a."
dfNorm.columns = newColumns

dfNorm.to_csv(path,sep="\t")

dfNorm

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
0,0,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"601,86","601,86","2,88","2,97",0,0,NaN,NaN,NaN,NaN
1,1,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"601,64","601,64","2,92","3,00",0,0,NaN,NaN,NaN,NaN
2,2,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"601,88","601,88","2,91","2,99",0,0,NaN,NaN,NaN,NaN
3,3,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"602,38","602,38","2,80","2,89",0,0,NaN,NaN,NaN,NaN
4,4,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"602,62","602,62","2,73","2,81",0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,211,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"594,07","594,07","3,02","3,12",0,0,NaN,NaN,NaN,NaN
212,212,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"594,06","594,06","2,98","3,09",0,0,NaN,NaN,NaN,NaN
213,213,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"593,91","593,91","2,98","3,09",0,0,NaN,NaN,NaN,NaN
214,214,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,NaN,NaN,NaN,NaN,4,4,NaN,NaN,NaN,NaN
215,215,n.a.,n.a.,n.a,n.a.,n.a.,n.a.,n.a.,321953,1920 x 1080,...,"593,44","593,44","2,89","3,02",0,0,NaN,NaN,NaN,NaN